#Requires -Version 7.2
<#+
.SYNOPSIS
Enables a staged Microsoft Entra ID employee account on or after the approved start date.

.DESCRIPTION
Consumes the approved onboarding package generated by the Great Gray Horizon employer onboarding admin.
The script refuses activation when required approval gates are incomplete, the package is not approved,
or the effective date is still in the future unless -OverrideStartDate is explicitly supplied.
#>
[CmdletBinding(SupportsShouldProcess = $true, ConfirmImpact = 'High')]
param(
    [Parameter(Mandatory = $true)]
    [ValidateScript({ Test-Path $_ -PathType Leaf })]
    [string]$InputFile,

    [Parameter(Mandatory = $true)]
    [ValidatePattern('^[0-9a-fA-F-]{36}$')]
    [string]$TenantId,

    [switch]$OverrideStartDate,
    [switch]$InstallMissingModules,
    [string]$AuditOutputPath = (Join-Path $PWD "ggh-access-activation-$(Get-Date -Format 'yyyyMMdd-HHmmss').json")
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

function Assert-GGHModule {
    param([Parameter(Mandatory)][string]$Name)
    if (-not (Get-Module -ListAvailable -Name $Name)) {
        if (-not $InstallMissingModules) {
            throw "Required module '$Name' is not installed. Install it first or rerun with -InstallMissingModules."
        }
        Install-Module -Name $Name -Scope CurrentUser -Repository PSGallery -Force -AllowClobber
    }
    Import-Module $Name -ErrorAction Stop
}

$package = Get-Content -Path $InputFile -Raw -Encoding UTF8 | ConvertFrom-Json -Depth 20
if ($package.status -ne 'APPROVED_FOR_IT_EXECUTION') {
    throw "Package must be APPROVED_FOR_IT_EXECUTION. Current status: $($package.status)"
}
if ($package.allGatesComplete -ne $true) {
    throw 'All approval and compliance gates must be complete before account activation.'
}
if (-not $package.candidate.employeeId) {
    throw 'The approved package is missing an Employee ID.'
}
if (-not $package.identity.userPrincipalName) {
    throw 'The approved package is missing a userPrincipalName.'
}

$startDate = [datetime]::Parse($package.employment.startDate).Date
if (-not $OverrideStartDate -and (Get-Date).Date -lt $startDate) {
    throw "The approved start date is $($startDate.ToString('yyyy-MM-dd')). Use -OverrideStartDate only with documented executive approval."
}

Assert-GGHModule -Name 'Microsoft.Graph.Authentication'
Assert-GGHModule -Name 'Microsoft.Graph.Users'
Assert-GGHModule -Name 'Microsoft.Graph.Groups'

$scopes = @(
    'User.ReadWrite.All',
    'User.EnableDisableAccount.All',
    'GroupMember.ReadWrite.All',
    'Directory.ReadWrite.All'
)
Connect-MgGraph -TenantId $TenantId -Scopes $scopes -NoWelcome
$context = Get-MgContext
if (-not $context -or $context.TenantId -ne $TenantId) {
    throw 'Microsoft Graph connection did not resolve to the requested tenant.'
}

$upn = [string]$package.identity.userPrincipalName
$user = Get-MgUser -UserId $upn -Property Id,DisplayName,UserPrincipalName,AccountEnabled,EmployeeId
if ($user.EmployeeId -ne [string]$package.candidate.employeeId) {
    throw 'Employee ID in Microsoft Entra ID does not match the approved onboarding package.'
}

$events = [System.Collections.Generic.List[object]]::new()
function Add-Event([string]$Action, [string]$Status, [hashtable]$Details = @{}) {
    $events.Add([ordered]@{
        eventId = [guid]::NewGuid().Guid
        timestamp = (Get-Date).ToUniversalTime().ToString('o')
        actor = [Environment]::UserName
        workstation = [Environment]::MachineName
        action = $Action
        status = $Status
        details = $Details
    })
}

Add-Event -Action 'ACTIVATION_PACKAGE_VALIDATED' -Status 'SUCCESS' -Details @{ packageId = $package.packageId; upn = $upn; employeeId = $user.EmployeeId }

foreach ($groupId in @($package.microsoft365.groupIds)) {
    if (-not $groupId) { continue }
    if ($groupId -notmatch '^[0-9a-fA-F-]{36}$') { throw "Invalid group object ID '$groupId'." }
    $reference = @{ '@odata.id' = "https://graph.microsoft.com/v1.0/directoryObjects/$($user.Id)" }
    try {
        if ($PSCmdlet.ShouldProcess($upn, "Ensure membership in group $groupId")) {
            New-MgGroupMemberByRef -GroupId $groupId -BodyParameter $reference
            Add-Event -Action 'GROUP_MEMBERSHIP_CONFIRMED' -Status 'ADDED' -Details @{ groupId = $groupId }
        }
    } catch {
        if ($_.Exception.Message -match 'already exist|added object references already exist|One or more added object references already exist') {
            Add-Event -Action 'GROUP_MEMBERSHIP_CONFIRMED' -Status 'ALREADY_MEMBER' -Details @{ groupId = $groupId }
        } else {
            throw
        }
    }
}

if ($PSCmdlet.ShouldProcess($upn, 'Enable Microsoft Entra ID account')) {
    Update-MgUser -UserId $user.Id -AccountEnabled:$true
    Add-Event -Action 'ENTRA_ACCOUNT_ENABLED' -Status 'SUCCESS' -Details @{ userId = $user.Id; upn = $upn; startDate = $package.employment.startDate }
}

$verified = Get-MgUser -UserId $user.Id -Property Id,DisplayName,UserPrincipalName,AccountEnabled,EmployeeId
if (-not $verified.AccountEnabled -and -not $WhatIfPreference) {
    throw 'Post-activation verification failed: accountEnabled is still false.'
}
Add-Event -Action 'POST_ACTIVATION_VERIFIED' -Status 'SUCCESS' -Details @{ accountEnabled = $verified.AccountEnabled }

$result = [ordered]@{
    schemaVersion = 1
    completedAt = (Get-Date).ToUniversalTime().ToString('o')
    tenantId = $TenantId
    packageId = $package.packageId
    employeeId = $package.candidate.employeeId
    userObjectId = $verified.Id
    userPrincipalName = $verified.UserPrincipalName
    accountEnabled = $verified.AccountEnabled
    events = $events
}
$result | ConvertTo-Json -Depth 20 | Set-Content -Path $AuditOutputPath -Encoding UTF8
Write-Host "Activation audit written to: $AuditOutputPath" -ForegroundColor Green
$result | ConvertTo-Json -Depth 20
Disconnect-MgGraph -ErrorAction SilentlyContinue | Out-Null
