const navItems=[['overview','Executive Overview'],['candidate','Candidate File'],['workflows','Workflow Orchestration'],['documents','Documents & Signatures'],['governance','Governance & Compliance'],['rbac','RBAC Matrix'],['support','Support Center'],['audit','Audit Trail']];
const seed={candidate:{name:'Jennifer Martin',email:'Jmartin@thesolastagroup.org',status:'Conditional Review',proposedTitle:'Chief Clinical & Program Development Officer',compensation:'$95,000–$125,000',readiness:42,identity:70,credential:25,ethics:39},tasks:[['Identity and résumé verification','Recruiting','IN PROGRESS'],['NJ license category and number','Compliance','BLOCKED'],['Conflict-of-interest disclosure','Ethics','PENDING'],['Offer and compensation approval','Executive','PENDING'],['I-9 and W-4 collection','HR','NOT STARTED'],['Corporate email provisioning','IT','GATED']],documents:[['Conditional Offer Letter','Offer','DRAFT'],['Executive Employment Agreement','Agreement','DRAFT'],['Partnership and Equity Term Sheet','Agreement','DRAFT'],['Confidentiality and IP Assignment','Compliance','READY'],['Background-Screening Disclosure','Disclosure','READY'],['Benefits Enrollment Packet','Benefits','GATED'],['Form I-9','Federal Form','GATED'],['Form W-4','Federal Form','GATED']],events:[['2026-08-04 23:11','Candidate identifier updated','Jmartin@thesolastagroup.org'],['2026-08-04 22:38','Ethics review initialized','Conditional review'],['2026-08-04 21:52','Branded document system created','Navy · Gold · Silver'],['2026-08-04 20:40','Due-diligence report generated','Evidence limitations recorded']]};
const permissions={CANDIDATE:['View own file','Upload documents','Sign assigned documents','Complete tasks','Use support'],RECRUITER:['View/edit candidate','Create tasks','Upload records','Manage interviews'],COMPLIANCE:['Verify credentials','Review disclosures','Approve compliance gate','View audit'],ETHICS:['Score ethics review','Review conflicts','Approve partnership gate'],HR:['Issue offer','Collect tax/benefit forms','Manage onboarding'],EXECUTIVE:['Approve title/pay/equity','Approve final appointment','View all'],IT_ADMIN:['Provision email after gates','Manage access','Revoke accounts'],AUDITOR:['Read-only evidence, workflow and audit access']};
const app=document.querySelector('#app'),title=document.querySelector('#page-title'),nav=document.querySelector('#nav');
function badge(x){const c=/SIGNED|READY|COMPLETED|APPROVED/.test(x)?'ok':/BLOCKED|HIGH|GATED/.test(x)?'danger':'warn';return `<span class="badge ${c}">${x}</span>`}
function route(page){location.hash=page;render(page)}
nav.innerHTML=navItems.map(([k,v])=>`<button data-page="${k}">${v}</button>`).join('');nav.addEventListener('click',e=>{if(e.target.dataset.page)route(e.target.dataset.page)});
function setActive(page){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));title.textContent=navItems.find(x=>x[0]===page)?.[1]||'Candidate Operations'}
function metrics(){return `<div class="grid grid-4"><div class="card metric"><strong>${seed.candidate.readiness}%</strong><span>Decision readiness</span></div><div class="card metric"><strong>${seed.candidate.identity}%</strong><span>Identity confidence</span></div><div class="card metric"><strong>${seed.candidate.credential}%</strong><span>Credential verification</span></div><div class="card metric"><strong>${seed.candidate.ethics}/100</strong><span>Ethics file completeness</span></div></div>`}
function overview(){return `${metrics()}<div class="section-title"><h2>Candidate snapshot</h2>${badge(seed.candidate.status.toUpperCase())}</div><div class="grid grid-2"><div class="card"><h3>${seed.candidate.name}</h3><p><b>Email:</b> ${seed.candidate.email}</p><p><b>Proposed role:</b> ${seed.candidate.proposedTitle}</p><p><b>Pay band:</b> ${seed.candidate.compensation}</p><div class="callout">No clinical authority, equity, banking access or protected-data access activates until credential, ethics, executive and security gates are complete.</div></div><div class="card"><h3>Onboarding completion</h3><div class="progress"><span style="width:${seed.candidate.readiness}%"></span></div><p>${seed.candidate.readiness}% of required verification and approval controls completed.</p><button class="button" onclick="location.hash='workflows';location.reload()">Open workflow center</button></div></div><div class="section-title"><h2>Current tasks</h2></div>${taskTable()}<div class="section-title"><h2>Latest audit events</h2></div>${timeline()}`}
function taskTable(){return `<table><thead><tr><th>Task</th><th>Owner</th><th>Status</th></tr></thead><tbody>${seed.tasks.map(t=>`<tr><td>${t[0]}</td><td>${t[1]}</td><td>${badge(t[2])}</td></tr>`).join('')}</tbody></table>`}
function timeline(){return `<div class="timeline">${seed.events.map(e=>`<div class="timeline-item"><b>${e[1]}</b><br><small>${e[0]} · ${e[2]}</small></div>`).join('')}</div>`}
function candidate(){return `<div class="grid grid-2"><div class="card"><h2>Identity profile</h2><p><b>Legal/professional name:</b> Jennifer Martin</p><p><b>Primary email:</b> ${seed.candidate.email}</p><p><b>Reported associations:</b> Lumberton, New Jersey; Crowley, Louisiana; Rider University</p><p><b>Evidence state:</b> Candidate-provided and partially corroborated; authoritative license identity pending.</p></div><div class="card"><h2>Position profile</h2><p><b>Interim title:</b> Proposed Clinical Programs Partner</p><p><b>Post-verification title:</b> ${seed.candidate.proposedTitle}</p><p><b>Recommended offer:</b> $90,000–$105,000 base, up to 10% incentive, milestone-based equity.</p></div></div><div class="section-title"><h2>Assessment domains</h2></div><table><thead><tr><th>Domain</th><th>Score</th><th>Interpretation</th></tr></thead><tbody><tr><td>Identity resolution</td><td>70</td><td>Moderate confidence; official identifiers required</td></tr><tr><td>Credential verification</td><td>25</td><td>License number and category unresolved</td></tr><tr><td>Professional alignment</td><td>55</td><td>Potentially aligned; résumé and references needed</td></tr><tr><td>Ethics review</td><td>39</td><td>File incomplete; not a character score</td></tr><tr><td>Cybersecurity readiness</td><td>30</td><td>Training, managed device and MFA not completed</td></tr></tbody></table>`}
function workflows(){return `<div class="callout"><b>Trigger rule:</b> Corporate email issuance begins only after signed offer, required disclosures, verification approvals, tax/benefits intake and security acknowledgment.</div><div class="section-title"><h2>Workflow pipeline</h2></div>${taskTable()}<div class="grid grid-2" style="margin-top:18px"><div class="card"><h3>Offer acceptance trigger</h3><ol><li>Executive approval</li><li>Candidate e-signature</li><li>Compliance and ethics clearances</li><li>HR forms released</li><li>IT provisioning task generated</li></ol></div><div class="card"><h3>Retention controls</h3><p>Each event receives actor, UTC timestamp, object identifier, prior event hash and current event hash. Legal hold overrides routine deletion.</p></div></div>`}
function documents(){return `<div class="section-title"><h2>Document registry</h2><button class="button">Upload document</button></div><table><thead><tr><th>Document</th><th>Category</th><th>Status</th><th>Action</th></tr></thead><tbody>${seed.documents.map(d=>`<tr><td>${d[0]}</td><td>${d[1]}</td><td>${badge(d[2])}</td><td><button class="button secondary">Open</button></td></tr>`).join('')}</tbody></table><div class="section-title"><h2>Signature control</h2></div><div class="card"><p>Signatures require signer intent, typed legal name, authenticated session, UTC timestamp, document hash and immutable audit event. Decorative signature images are never the controlling evidence.</p></div>`}
function governance(){return `<div class="grid grid-2"><div class="card"><h2>Mission</h2><p>Deliver dignified, accountable, inclusive and technology-enabled counseling-program administration, education and community support while preserving professional scope, privacy and due process.</p></div><div class="card"><h2>Corporate paradigm</h2><p>Ross Tax Pro Software Co. supplies technology, governance, auditability and operational support. Clinical authority remains with properly credentialed professionals acting within jurisdiction and scope.</p></div></div><div class="section-title"><h2>Policy library</h2></div><table><thead><tr><th>Policy</th><th>Owner</th><th>Review cycle</th></tr></thead><tbody>${['Code of Ethics|Ethics Committee|Annual','Clinical Scope and Credentialing|Compliance|Quarterly','Data Privacy and Security|Security Office|Quarterly','Electronic Signatures and Records|Legal/IT|Annual','Conflicts of Interest|Board|Annual','Candidate Screening and Fairness|HR/Legal|Annual','AI Acceptable Use|Technology Governance|Quarterly','Incident Response|Security Office|Semiannual'].map(x=>{const p=x.split('|');return `<tr><td>${p[0]}</td><td>${p[1]}</td><td>${p[2]}</td></tr>`}).join('')}</tbody></table>`}
function rbac(){return `<div class="section-title"><h2>Roles and permissions</h2></div>${Object.entries(permissions).map(([r,ps])=>`<div class="card" style="margin-bottom:14px"><h3>${r}</h3><p>${ps.join(' · ')}</p></div>`).join('')}`}
function support(){return `<div class="grid grid-2">${[['Candidate Concierge','Portal navigation, forms, deadlines and accessibility routing'],['HR Onboarding Agent','Offer, tax-form and benefits workflow support'],['Compliance Desk','Credential, disclosure and policy guidance'],['Security Help Agent','MFA, device, account and incident support'],['Executive Operations Agent','Approval queues, compensation and governance routing'],['Clinical Policy Agent','Scope, supervision and documentation guidance; escalates clinical decisions']].map(p=>`<div class="card"><h3>${p[0]}</h3><p>${p[1]}</p><button class="button">Start assisted session</button></div>`).join('')}</div><p class="footer-note">Agents provide policy-grounded administrative support and route legal, clinical, payroll, benefits and security decisions to authorized humans.</p>`}
function audit(){return `<div class="section-title"><h2>Append-only event stream</h2><button class="button secondary">Export JSON/CSV</button></div><table><thead><tr><th>UTC time</th><th>Event</th><th>Detail</th></tr></thead><tbody>${seed.events.map(e=>`<tr><td>${e[0]}</td><td>${e[1]}</td><td>${e[2]}</td></tr>`).join('')}</tbody></table><div class="callout" style="margin-top:18px">Production mode stores actor, object, action, source IP where lawful, device/session ID, prior hash, event hash, retention class and legal-hold status.</div>`}
const pages={overview,candidate,workflows,documents,governance,rbac,support,audit};
function render(page='overview'){page=pages[page]?page:'overview';setActive(page);app.innerHTML=pages[page]();}
window.addEventListener('hashchange',()=>render(location.hash.slice(1)));render(location.hash.slice(1)||'overview');
